defaults:
- hydra/launcher: submitit_slurm
- hydra/hydra_logging: colorlog

net:
  model: votenet
  is_train: False
  backbone: sparseconv # pointnet2
  weights:
  num_target: 256
  vote_factor: 1
  cluster_sampling: vote_fps

data:
  dataset: sunrgbd
  data_ratio: 1.0
  num_points: 20000
  num_workers: 4
  batch_size: 8
  no_height: True # False
  use_color: False
  use_sunrgbd_v2: False
  overwrite: False
  voxelization: True # False
  voxel_size: 0.05
  shuffle_datast: False

optimizer:
  max_epoch: 180
  learning_rate: 0.001
  lr_decay_steps: [80, 120, 160]
  lr_decay_rates: [0.1, 0.1, 0.1]
  weight_decay: 0
  bn_decay_step: 20
  bn_decay_rate: 0.5

test:
  use_3d_nms: False
  use_cls_nms: False
  use_old_type_nms: False
  per_class_proposal: False
  nms_iou: 0.25
  conf_thresh: 0.05
  faster_eval: False, #Faster evaluation by skippling empty bounding box removal.
  ap_iou_thresholds: [0.25, 0.5]

misc:
  log_dir: log
